name: flsah ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

        # with:
        #   username: ${{ secrets.QUAY_USERNAME }}
        #   password: ${{ secrets.QUAY_PASSWORD }}

      - name: Log in to Quay.io
        run: echo ${{ secrets.QUAY_PASSWORD }} | podman login quay.io -u ${{ secrets.QUAY_USERNAME }} --password-stdin

      - name: Docker image build
        run: |
          uses: podman build . --file dockerfile -tag quay.io/${{ secrets.QUAY_USERNAME }}/python-app:$(date +%s)

      - name: Docker push
        run: |
          podman push quay.io/${{ secrets.QUAY_USERNAME }}/python-app:$(date +%s)