name: flsah ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Set image tag
        id: tag_step
        run: echo "::set-output name=tag::$(date +%s)"


      - name: Log in to Quay.io
        run: echo ${{ secrets.QUAY_PASSWORD }} | podman login quay.io -u ${{ secrets.QUAY_USERNAME }} --password-stdin

      - name: Docker image build
        run: podman build -t quay.io/${{ secrets.QUAY_USERNAME }}/python-app:${{ steps.tag_step.outputs.tag }}  -f Dockerfile .

      - name: Docker push
        run: podman push quay.io/${{ secrets.QUAY_USERNAME }}/python-app:${{ steps.tag_step.outputs.tag }} 
      