name: flsah ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: quay login
        uses: podman/login-action@v4
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      

      - name: Docker image build
        run: |
          cd ./flash
          uses: podman build . --file dockerfile -tag quay.io/${{ secrets.QUAY_USERNAME }}/${{ secrets.QUAY_PASSWORD }}:$(date +%s)

      - name: Docker push
        run: |
          podman push quay.io/${{ secrets.QUAY_USERNAME }}/${{ secrets.QUAY_PASSWORD }}:$(date +%s)